version: "3"
services:
  postgres-server:
    image: "postgres"
    container_name: time-tracker-db-dev
    ports:
      - "6543:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  node-app:
    container_name: time-tracker-be-dev
    depends_on:
      - postgres-server
    build:
      dockerfile: Dockerfile.dev
      context: .
    volumes:
      - ./:/app
    ports:
      - 4100:4100
    environment:
      - POSTGRES_HOST=postgres-server
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - PORT=4100
  migration:
    build:
      context: .
    command:
      [
        "./wait-for-it/wait-for-it.sh",
        "postgres-server:5432",
        "--",
        "npm",
        "run",
        "migrate",
        "up"
      ]
    links:
      - postgres-server
    depends_on:
      - postgres-server
    environment:
      - DATABASE_URL=postgres://postgres:"123"@postgres-server:5432/postgres
